$(function(){
	$('#myForm').ajaxForm({
		beforeSend:function(){
			$(".progress").show();
			
		},
		uploadProgress:function(event,position,total,percentComplete){
			$(".progress-bar").width(percentComplete+'%');
			$(".sr-only").html(percentComplete+'%');
		},
		success:function(){
			$(".progress").hide();
		},
		complete:function(response){
			$(".progress").hide();
			$("#name").val("");
			$("#price").val("");
			$("#desc").val("");
			$("#stock").val("");
			$("#successAlert").show().delay(1000).fadeOut();
		}
	});
	$("#successAlert").hide();
	$(".progress").hide();
});